"""guest checkout, returns, is_active

Revision ID: 4e099cec0ff4
Revises: c3ad36d99708
Create Date: 2026-09-04 08:47:07.118528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e099cec0ff4'
down_revision = 'c3ad36d99708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False,
               server_default=sa.true()))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('return_status', sa.String(length=20), nullable=False,
               server_default='none'))
        batch_op.add_column(sa.Column('return_reason', sa.Text(), nullable=True))
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('return_reason')
        batch_op.drop_column('return_status')
        batch_op.drop_column('guest_email')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
